### ISSUE TITLE
Compatibility with series 4 PCBs

### ISSUE THREAD

**Issue by Rezoran** [14yannick/hoermann_door#2]
Hi there,

I have made a fork from your projects since you have done a very good job at porting esphome to this project!

From other sources such as https://github.com/steff393/hgdo I have made an attempt to get the old E3 drives to work with the simple hardware designed for the 4 Series units.

You can see the results here: https://github.com/Rezoran/hoermann_door

I have tested (as stated in the README) with a salvaged RS485 transceiver and an esp32dev with plain serial on it while also utilizing the rts pin.
Works very well so far and I haven't had any timing or other issues so I would consider this an easier alternative.

The main reason I created this issue is that I would want to merge the two components together to reduce the maintenance needed to maintain those fairly similar projects. 
I mostly kept the sub-component files the same and since I am not that firm in esphome, I hope that there is a mechanic to allow i.e. the [uapbridge_pic16_cover.cpp](https://github.com/14yannick/hoermann_door/blob/main/esphome/components/uapbridge_pic16/cover/uapbridge_pic16_cover.cpp) code to use both uapbridges and therefore reduce the redundancies.

If this is a possibility and you are interested, I think I will be able to create a PR for that (would be my first one)

**Comment by 14yannick** [comment]
Hi Rezoran,
Nice job had also in mind to port the hgdo project to Esphome to be able to use easier hardware. I personally have an E4 motor so I have a couple different hardware I can try your project on. 
I think it should be possible to merge our two implementation I not sure how but will ask on discord. I think I will first add manually your component in my repo if it's ok for you. I will clean up my repo a bit. That will allow an easier creation of PR. Because if you create now a PR will delete the pic16 component. 
I saw that you use the autocorrect function of the hgdo code. Do you know if the function is triggered often?

**Comment by Rezoran** [comment]
Hi Yannick,
I think I figured a way out to merge the two components by now. Give me a few days and I will create a PR with a new branch (cleaned up commits and as one component), that won't overwrite and remove the pic16 implementation.
It triggers quite often I think. Aspecially on a powercycle/outage and if I loose an answer frame (OTA etc.) but has always healed itself without notice, so that the light didn't even flicker.
I also added a working stop method after a bit of trial and error that won't generate an error.

**Comment by 14yannick** [comment]
Hi, yes maybe a similar approach is needed as for the bme sensor for example. ther you have a base and then a different component if it's i2c or spi protocol.
<img width="775" alt="image" src="https://github.com/user-attachments/assets/81ce1111-b9e4-4631-a3bc-4e217f9edd49">
Yes regarding the stop I'm also working on it. I was thinking to use the impulse command only if the door is moving.
`0x1004`
```
    case hoermann_action_soft_stop: {
      if ((broadcast_status & 0x60) == 0x40 || (broadcast_status & 0x60) == 0x60) {
        slave_respone_data = RESPONSE_IMPULSE;
      }
      break;
```
I saw that you use the `0x10FF`  with the same logic only to send the command on a moving door.
Did you have tried the impulse command to stop the door? What happen if you send the code 0x10FF on a non moving door?

**Comment by Rezoran** [comment]
Thats exactly the project I am looking at while porting both solutions. I am relatively confident that I can finish the PR using that base architecture this weekend.
Regarding the stop, I tried a few things including masking a few bits with the open and close action (like the moving and direction bits) but nothing really worked. 
Using the impulse will just reverse the direction in which the door is traveling (I think only while closing, but I am not 100% sure anymore). 
Best working mechanism was 0x00FF but that caused an issue (the 0x10 is something like a dead man switch that is set by the UAP and has to be always set to prevent errors),  so 0x10FF works very well in case of stopping while moving. 
I don't really know why it does it; I tried a few combinations of bits there to get the one combination that only does what it should, but ultimately only 0x10FF seems to stop the door reliably. 
Since this also starts the door when it's stopped already, I think it is an unhandled combination of bits that does it but that's just a guess.
So yes it also starts the door while it's not moving.

**Comment by 14yannick** [comment]
I have added the change I have locally in the merged [wip](https://github.com/14yannick/hoermann_door/tree/wip) branch.
I have done a small change implementing the toggle (Impulse) functionality also in your component.

**Comment by 14yannick** [comment]
I'trying to fixe an issue where the state of the light in home assistant does not corresponding to the actual state of the light.
It seems that the [on_event](https://github.com/14yannick/hoermann_door/blob/2a0dd881d7ff96105c9b76ad174d1fef64f7f0dd/esphome/components/uapbridge/light/uapbridge_light.cpp#L31) function gets not triggered. But I don't see why. Does it work on your board? For example when your door start to move does your light in HAS get's turned on?

**Comment by Rezoran** [comment]
I'll check that tomorrow at my garage but there was one bug in your yaml that set the wrong platform for the light sensor ( binary instead of uapbridge) maybe you have that in your yaml as well. Otherwise it may be related to the setcallback function in the base class or the interfacing variables.
I'll let you know tomorrow if it works at my door. Prior to the base class, it definitely worked

**Comment by 14yannick** [comment]
Thx you nailed it.

**Comment by 14yannick** [comment]
Merged in main an create a release based on it.
[Tag v1.0.0](https://github.com/14yannick/hoermann_door/releases/tag/v1.0.0)
Thx for your work
